reward:
  max_reward: 2.0
  components:
    - name: openai_moderation
      id: illicit
      role: retain
      params: {category: illicit}
    - name: cached_openai_moderation
      id: sexual
      role: forget
      params: {category: sexual}

rh_detector:
  name: cached_openai_moderation
  params:
    category: sexual
    threshold: 0.4
